# Generated by Django 4.2.3 on 2023-07-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0002_alter_token_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(max_length=350),
        ),
    ]
