# Generated by Django 4.2.3 on 2023-07-27 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0003_alter_token_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="user_id",
            new_name="user",
        ),
    ]
