# Generated by Django 4.2.3 on 2023-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0008_alter_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
        migrations.AddField(
            model_name="user",
            name="tokens",
            field=models.JSONField(max_length=350, null=True),
        ),
    ]
