# Generated by Django 4.2.3 on 2023-07-27 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0009_remove_user_token_user_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="payload",
        ),
    ]
