# Generated by Django 4.2.3 on 2023-07-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0010_remove_api_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rbac_app.user"
            ),
        ),
    ]
