# Generated by Django 4.2.3 on 2023-08-01 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0014_alter_api_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api",
            old_name="roles",
            new_name="mapped_users",
        ),
    ]
